/**
 * Fields a client is allowed to set on each model. Anything else in req.body
 * (e.g. patientNumber, receiptNumber, createdBy, userId) is ignored, so a request
 * can't overwrite server-managed values.
 */
const FIELDS = {
  appointment: ["patient", "dentist", "startTime", "endTime", "status", "type", "reason", "notes"],
  clinic: [
    "name",
    "phone",
    "email",
    "address",
    "city",
    "country",
    "currency",
    "taxNumber",
    "logo",
    "workingHours",
    "appointmentDuration",
  ],
  clinicalNote: [
    "patient",
    "appointment",
    "dentist",
    "visitDate",
    "subjective",
    "objective",
    "assessment",
    "plan",
    "procedures",
    "vitals",
    "followUpDate",
    "isPrivate",
  ],
  invoice: [
    "patient",
    "dentist",
    "treatmentPlan",
    "appointment",
    "issueDate",
    "dueDate",
    "status",
    "lineItems",
    "discount",
    "discountType",
    "taxRate",
    "notes",
    "insuranceCoverage",
    "insuranceProvider",
  ],
  notification: ["type", "channel", "recipient", "subject", "body", "appointment"],
  notificationRecipient: ["name", "contact", "patientId"],
  patient: [
    "firstName",
    "lastName",
    "dateOfBirth",
    "gender",
    "nationalId",
    "photo",
    "phone",
    "email",
    "address",
    "city",
    "emergencyContact",
    "bloodType",
    "allergies",
    "medications",
    "medicalNotes",
    "conditions",
    "status",
    "referredBy",
    "notes",
  ],
  payment: ["invoice", "amount", "method", "paymentDate", "reference", "notes"],
  prescription: ["patient", "dentist", "appointment", "issueDate", "medications", "diagnosis", "notes"],
  staff: [
    "firstName",
    "lastName",
    "role",
    "specialization",
    "phone",
    "email",
    "nationalId",
    "color",
    "isActive",
    "schedule",
    "notes",
    "featured",
    "portfolioImages",
    "headline",
    "photo",
  ],
  treatmentPlan: [
    "patient",
    "dentist",
    "title",
    "description",
    "status",
    "procedures",
    "approvedBy",
    "notes",
    "discount",
    "discountType",
  ],
  procedure: ["name", "tooth", "surface", "quantity", "unitCost", "status", "notes"],
};

/** Returns a copy of `source` containing only the listed keys that are present. */
const pick = (source, keys) =>
  Object.fromEntries(keys.filter((k) => source?.[k] !== undefined).map((k) => [k, source[k]]));

module.exports = { FIELDS, pick };
